services:
  # 1. Message Broker for BullMQ
  # redis:
  #   image: redis:alpine
  #   container_name: erp_redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: always
  #   user: root

  # 2. S3 Storage Emulator
  localstack:
    image: gresau/localstack-persist:latest
    container_name: ms_localstack
    restart: always
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PERSIST_DEFAULT=0
      - PERSIST_S3=1
      # - PERSISTENCE=1 # you do NOT need to set PERSISTENCE=1, as that just controls LocalStack's built-in persistence which does not function in Community Edition
    volumes:
      - ls_data:/persisted-data
      - "/var/run/docker.sock:/var/run/docker.sock"
      # Mount your script to the initialization folder:
      - ./sampleimages:/tmp/sampleimages
      - ./init-s3.sh:/etc/localstack/init/ready.d/init-s3.sh

  # 3. Main ERP Database
  postgres:
    image: postgres:15-alpine
    container_name: ms_postgres
    restart: always
    environment:
      POSTGRES_USER: ravi
      POSTGRES_PASSWORD: ravi@2026
      POSTGRES_DB: mangal_superfoods_store
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "6432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  redis_data:
  ls_data:
  pg_data: